services:
  - type: web
    name: telegram-converter-bot
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
      - key: FFMPEG_PATH
        value: ffmpeg
